"""
MedGuard AI - Maintenance Decision Agent

Combines:
    XGBoost prediction
    SHAP explanation
    Equipment context

and produces:
    Risk level
    Maintenance priority
    Recommendation
    Alert
    Human review requirement
"""

from typing import Dict, Any, List

from agent.risk_engine import build_risk_decision


def generate_recommendation(
    risk_level: str,
    top_factors: List[Dict[str, Any]]
) -> str:
    """
    Generate a maintenance recommendation using
    the risk level and SHAP factors.
    """

    factor_names = []

    for factor in top_factors[:3]:
        feature = factor.get("feature")

        if feature:
            feature = feature.replace("_", " ")
            factor_names.append(feature)

    factor_text = ", ".join(factor_names)

    if risk_level == "CRITICAL":

        if factor_text:
            return (
                "Schedule an urgent inspection. "
                f"Review the main risk factors: {factor_text}. "
                "Verify equipment condition before continued operation."
            )

        return (
            "Schedule an urgent inspection and verify "
            "equipment condition before continued operation."
        )

    elif risk_level == "HIGH":

        if factor_text:
            return (
                "Prioritize maintenance inspection. "
                f"Review the main risk factors: {factor_text}."
            )

        return (
            "Prioritize maintenance inspection and "
            "review recent equipment history."
        )

    elif risk_level == "MEDIUM":

        if factor_text:
            return (
                "Monitor the equipment and review the "
                f"contributing factors: {factor_text}. "
                "Schedule maintenance if the risk increases."
            )

        return (
            "Continue monitoring and schedule maintenance "
            "if the risk increases."
        )

    else:

        return (
            "No immediate maintenance action is required. "
            "Continue routine monitoring and preventive maintenance."
        )


def generate_alert(
    risk_level: str,
    probability: float
) -> Dict[str, Any]:
    """
    Generate an alert for HIGH or CRITICAL risk.
    """

    alert_required = risk_level in [
        "HIGH",
        "CRITICAL"
    ]

    if not alert_required:

        return {
            "created": False,
            "severity": None,
            "message": None
        }

    percentage = round(
        probability * 100,
        1
    )

    return {
        "created": True,
        "severity": risk_level,
        "message": (
            f"Critical-risk score is {percentage}%. "
            "Human review is required."
        )
    }


def run_maintenance_agent(
    prediction: Dict[str, Any],
    shap_explanation: Dict[str, Any],
    equipment: Dict[str, Any] = None
) -> Dict[str, Any]:
    """
    Main Agent function.

    Parameters
    ----------
    prediction:
        Output generated by the ML prediction service.

    shap_explanation:
        Output generated by SHAP.

    equipment:
        Optional equipment information.

    Returns
    -------
    dict
        Complete maintenance decision.
    """

    if equipment is None:
        equipment = {}

    # --------------------------------------------------------
    # Get model probability
    # --------------------------------------------------------

    probability = float(
        prediction.get(
            "critical_risk_probability",
            shap_explanation.get(
                "critical_risk_probability",
                0
            )
        )
    )

    # --------------------------------------------------------
    # Get SHAP factors
    # --------------------------------------------------------

    top_factors = shap_explanation.get(
        "top_factors",
        []
    )

    # --------------------------------------------------------
    # Equipment context
    # --------------------------------------------------------

    equipment_criticality = equipment.get(
        "criticality",
        "NORMAL"
    )

    days_since_maintenance = int(
        equipment.get(
            "days_since_maintenance",
            0
        )
    )

    # --------------------------------------------------------
    # Risk decision
    # --------------------------------------------------------

    decision = build_risk_decision(
        critical_risk_probability=probability,
        equipment_criticality=equipment_criticality,
        days_since_maintenance=days_since_maintenance
    )

    # --------------------------------------------------------
    # Maintenance recommendation
    # --------------------------------------------------------

    recommendation = generate_recommendation(
        risk_level=decision["risk_level"],
        top_factors=top_factors
    )

    # --------------------------------------------------------
    # Alert
    # --------------------------------------------------------

    alert = generate_alert(
        risk_level=decision["risk_level"],
        probability=probability
    )

    # --------------------------------------------------------
    # Final Agent response
    # --------------------------------------------------------

    return {

        "risk": {
            "critical_risk_probability":
                decision["critical_risk_probability"],

            "risk_level":
                decision["risk_level"]
        },

        "maintenance": {
            "priority":
                decision["maintenance_priority"],

            "recommendation":
                recommendation
        },

        "alert": alert,

        "human_review_required": True
    }


# ============================================================
# DIRECT TEST
# ============================================================

if __name__ == "__main__":

    import json

    # Example ML output
    prediction = {
        "critical_risk_probability": 0.785466,
        "predicted_critical": 1
    }

    # Example SHAP output
    shap_explanation = {
        "top_factors": [
            {
                "feature": "recall_count",
                "shap_value": 0.5191,
                "direction": "increases risk"
            },
            {
                "feature": "classification_Unknown",
                "shap_value": 0.4400,
                "direction": "increases risk"
            },
            {
                "feature": "risk_class_2",
                "shap_value": 0.2359,
                "direction": "increases risk"
            }
        ]
    }

    equipment = {
        "equipment_id": "PUMP-042",
        "criticality": "CRITICAL",
        "days_since_maintenance": 48
    }

    result = run_maintenance_agent(
        prediction=prediction,
        shap_explanation=shap_explanation,
        equipment=equipment
    )

    print(
        json.dumps(
            result,
            indent=4
        )
    )